version: "3.9"
services:
  web:
    image: "clglavan/private-notes:latest"
    env_file:
      - .env
    ports:
      - "80:80"
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

# this application does and will not:
# - handle SSL, do this in a proxy before reaching private notes, in your own secure manner
# - serve assets like the logo image and any future ones
